### ISSUE TITLE
Example wrongly has `8/17` io `8, 17`

### ISSUE THREAD

**Issue by jamadagni** [tcbrindle/rational#1]
https://github.com/tcbrindle/rational/blob/4f2f604d48aefdaf394a5b6c9044486c78744e11/example/example.cpp#L55

I think this line should in fact read:

`rational<int>{8, 17} < rational<int>{1, 2}`

I think what is happening in fact is that `8/17` is evaluated by integer division as the integer value 0 which is < 1⁄2. If we change the `8/17` above to `8/15` it would still work for this same reason though 8⁄15 is not < 1⁄2. But changing it to `8, 15` then it fails:

    example.cpp:55:5: error: static_assert failed due to requirement 'tcb::rational<int>{8, 15} < tcb::rational<int>{1, 2}'

**Comment by tcbrindle** [comment]
Wow, I didn't know anyone was looking at this old code! :)

Yes, this definitely looks like a typo and the first term should be `rational<int>{8, 17}`.

**Comment by tcbrindle** [comment]
This should now be fixed, thanks for letting me know

**Comment by jamadagni** [comment]
Hi thanks for fixing this. But if this is old code, is there any other
newer simple implementation of rational that I might want to use? Yours was
one of the higher results. I don't want to pull in Boost.

**Comment by tcbrindle** [comment]
I'm afraid I don't know of any others apart from Boost.Rational. 

I haven't looked at this code for 7 years, and I don't think many other people have either as this is the first ever bug report! :) But if you want to use it I'll try to fix any other bugs you might find. Looking at it again, I see a couple of things to note:
 
 * This uses the pre-standard Concepts TS syntax which is no longer supported in C++20 (this shouldn't be a problem though, it just means you can't use the `Rational` concept)
 * If I were writing this today, I'd be much more careful about trying to avoid integer overflow in various calculations -- you might run into trouble with very large numerators or denominators

Sorry I can't be of more help!
